### ISSUE TITLE
can not get it to work

### ISSUE THREAD

**Issue by lucifier2003** [smahesh29/Weather-App#1]
![ss](https://user-images.githubusercontent.com/59222441/71444701-56236200-2739-11ea-99b0-ded2d4d8928c.PNG)
![fbS](https://user-images.githubusercontent.com/59222441/71444705-5885bc00-2739-11ea-9e75-cd6ad1836b3f.PNG)

what does this mean??????

**Comment by smahesh29** [comment]
You need to install requests module in your system. Use command  `pip install requests` to install it.
